FROM ruby:2.4
WORKDIR /usr/src/app
COPY Gemfile* ./
RUN bundle install
COPY . .

CMD [ \
     "./insanity-uploader.rb", \
     "--config", "secrets-staging.yml", \
     "--dryrun", \
     "-l", "1", \
     "--par-report","http://ieee802.org/1/files/public/insanity/pars-to-add.yml", \
     "--mailserv", \
     "--sb", \
     "--drafts", \
     "--slackpost" \
    ]
